project:
  type: website
  output-dir: docs

website:
  title: "Gurpreet Johl"
  description: "This is Gurpreet Johl's personal website."
  # TODO: maybe add a sidebar later if I have enough content to require it.
  # sidebar:
  #   style: "docked"
  #   search: true
  #   contents:
  #     - section: "Basics"
  #       contents:
  #         - index.qmd
  #         - basics-knitr.qmd
  #         - basics-jupyter.qmd
  navbar:
    search: true
    left:
    - text: Blog
      href: blog.qmd
    # - text: Projects
    #   href: projects.qmd
    right:
    - icon: github
      href: https://github.com/gjohl
    - icon: linkedin
      href: https://www.linkedin.com/in/gurpreetjohl
    - icon: twitter
      href: https://twitter.com/gurpreetjohl
format:
  html:
    theme: journal
    css: styles.css
