---
title: "Mathematical Statistics"
description: "Stats"
date: "2025-08-20"
categories: [Maths, Statistics]
---

# Distributions

## Bernoulli Distribution

A Bernoulli distribution describes an experiment that has two possible outcomes, i.e. success/failure, heads/tails, etc.

$$
X \sim \text{Bernoulli}(p)
$$

The probability of the successful and unsuccessful outcomes are:
$$
P(X=1) = p
$$
$$
P(X=0) = 1-p
$$

The sample space is:
$$
P \in [0,1]
$$

The sample space is also known as the **support**.

We can alternatively write this as a probability mass function (PMF):

$$
f(x) = 
\begin{cases}
p & x = 1 \\[6pt]
1-p & x = 0 \\[6pt]
0 & \text{otherwise}
\end{cases}
$$

A way of rewriting this is:
$$
f(x) = p^{x} (1-p)^{\,1-x}
$$


## The Uniform Distribution

This is a continuous distribution where every value between and min and a max value is equally likely.

$$
X \sim \text{Uniform}(a,b)
$$

As this is a continuous distribution, the *mass* of any point is infinitesimally small, so we have a probability density function (PDF) rather than a probability mass function (PMF).

$$
f(x) =
\begin{cases}
\dfrac{1}{b-a} & a \leq x \leq b \\[6pt]
0 & \text{otherwise}
\end{cases}
$$

The sample space is:
$$
S = (a, b)
$$


## Normal Distribution
Centred on the mean $\mu$. The spread is defined the standard deviation $\sigma$.

It is defined by these two parameters.

$$
f(x)= …
$$


# Expected Value

## Sample mean and Expected Value

For a sample, we have a sample mean depending on our observations. It changes each time we observe more data. 
$$
\bar{x} = (\sum_{i=1}_n x_i) / n
$$

The aim is to collect enough data that this is a reasonable approximation of the true population mean.

For a population, we have the expected value $$
E(X) = \mu
        = \sum_{x \in S} xP(X=x)
$$

Or for a continuous distribution
$$
E(X) = \integral_{x \in S} xf(x) dx
$$


## Expected value of a Bernoulli random variable

Recall the PMF:
```
f(x) = {p,    x=1
           1-p, x=0
           0,     otherwise
```

And the definition of expectation:
$$
E(X) = \mu
        = \sum_{x \in S} xP(X=x)
$$

So:
$$
E(X) = 0*(1-p) + 1*p
$$


## Expected value of a uniform random variable

This is continuous, so we integrate the PDF:

Expected value for a continuous distribution
$$
E(X) = \integral_{x \in S} xf(x) dx
         = \integral_{x=0}_{\theta} x.(1/\theta) dx
         = (1/ \theta) (x^2 / 2) |_{0}_{\theta}
         =  (1/ \theta) (\theta^2 / 2)
         = \theta / 2
$$


## Expected value for a Normal random variable

Again, this is a continuous distribution, so we can integrate the PDF.
See here for the integral: https://statproofbook.github.io/P/norm-mean.html

Intuitively, we know that a Normal distribution is symmetric and defined by \mu and \sigma.
So the expected value is \mu.

<Add worksheet>


# Estimators and Method of Moments

The goal in a lot of statistics is to learn (estimate) some unknown parameters.

- **Estimand** - the parameter we want to estimate. E.g. p, \mu, \theta
- **Estimate** - a concrete value of our estimand based on the data. E.g. 0.4, 3, 12
- **Estimator** - how do we get a good estimate for a particular distribution.

We want a method that allows us to create a good estimate. A formula/algorithm that allows us to estimate an estimand.
It takes data as inputs and outputs an estimate of a parameter.

The method of moments is one such estimator method.
It relies on the 1st moment: the expected value.

We begin with two facts:

1. $E(X) = f(\theta)$ - the expected value is some function of the parameters
2. $E(X) ~= X_bar$ - the sample mean should be approximately the population mean

Therefore we can substitute these:
$X_bar ~= f(\theta) 

X_bar is a known value calculated from our data. So this gives us an equation where $\theta$ is our unknown variable that we solve for.

## Method of Moments Estimator for a Bernoulli Distribution

We start with our two basic facts:

1. $E(X) ~= x_bar$ - our sample mean should be close to our population mean
2. $E(X) = p$ - for a Bernoulli distribution, the population mean is p

Substituting this, we get an estimate of the parameter $p$ using the method of moments:
$$
p ~= x_bar
$$

Note the approximately equal sign in the equation above. We don’t know the true population parameter so it isn’t equal, only an approximation. 

We can define this estimate as $p_hat$, which is defined as being equal to this estimate.

$$
p_hat = x_bar = (\sum x_i) / n
$$


## Method of Moments Estimator for a Uniform Distribution

We start with our two basic facts:

1. $E(X) ~= x_bar$ - our sample mean should be close to our population mean
2. $E(X) = \theta / 2$ - population mean for a uniform distribution

So we can substitute this to get our method of moments estimator for $\theta$:
$$
\theta / 2 ~= x_bar
=> \theta ~= 2 x_bar
=> \theta_hat = 2 x_bar
$$


## Method of Moments Estimator for a Normal Distribution
We start with our two basic facts:

1. $E(X) ~= x_bar$ - our sample mean should be close to our population mean
2. $E(X) = \mu$ - population mean for a Normal distribution

Therefore, we substitute to get our method of moments estimator for $\mu$:
$$
\mu ~= x_bar
\mu_hat =x_bar
$$


# Unbiased Estimators

## Distribution of estimators
Our data is random. It is the input to our estimator, therefore our estimate is also a random variable.

The distribution of an estimator is called a **sampling distribution**.

We want the estimator to be centred on the true value. This is an **unbiased estimator**. 
In other words, we want the expected value of the estimate to equal its true value, i.e. we want
$$
E(\theta_hat) = \theta
$$

We can define the **bias** as the difference between these two:
$$
Bias = E(\theta_hat) - \theta
$$

If $Bias = 0$ then we have an unbiased estimator.


## Properties of Expected Value
The linearity of expectation results below help us prove properties of the estimators. 

The law of the unconscious statistician:
$$
E(cX) = cE(X)
Where c is a constant
$$

This follows from the definition of expected value. E.g. for a discrete distribution:
$$
E(X) = \sum_{x \in S} xP(X=x)
=> E(cX) = \sum_{x \in S} cxP(cX=cx)
                = \sum_{x \in S} cxP(X=x)  since P(cX=cx) = P(X=x), multiplying the random variable just cancels out
                = c \sum_{x \in S} xP(X=x)
                = cE(X)
$$


The sum of random variables:
$$
E(X+Y) = E(X) + E(Y)
$$

Or more generally, the expected value of any sum equals the sum of expected values:

$$
E(\sum x_i) = \sum(E(x_i))
$$


## The bias of a MoM Estimator for a Bernoulli Distribution
Recall that our method of moments estimator was:
$$
p_hat = x_bar
$$

We want to know if this equals $E(p)$. This would make it an unbiased estimator.

$$
E(p_hat) = E(\sum x_i / n)
               = 1/n E(\sum(x_i))
               = 1/n \sum(E(x_i))  Using the sum of expected values result
               = 1/n \sum_{i=1}_n p
               = p 
$$

The expected value of our estimator is the population value, therefore it is an unbiased estimator.


## The bias of a MoM Estimator for a Uniform Distribution

Recall that our method of moments estimator is:
$$
\theta_hat = 2 x_bar
$$

So the expected value of the estimate is:
$$
E(\theta_hat) = E(2 x_bar)
                       =  E(2 \sum_{i=1}_{n} x_i / n)  
                       = 2/n E( \sum_{i=1}_{n} x_i )  Taking constant terms outside
                       = 2/n  \sum_{i=1}_{n} E(x_i)  Expectation of sum equals sum of expectations  
                       = 2/n  \sum_{i=1}_{n} \theta / 2  Substitute expression for E(x_i) 
                       = 2/n  * n \theta / 2
                       = \theta 
$$

Therefore, this is an unbiased estimator, because $E(\theta_hat) = \theta


## The bias of a MoM Estimator for a Normal Distribution

Recall that:
$$
\mu_hat = x_bar
$$

The expected value of this estimator is:
$$
E(\mu_hat) = E(x_bar)
                    = E( \sum_{i=1}_{n} x_i / n) 
                    = 1/n \sum_{i=1}_{n} E(x_i)  Sum of expectations is expectation of sums
                    = 1/n \sum_{i=1}_{n} \mu
                    = 1/n n* \mu
                     =  \mu 
$$

Therefore, this is an unbiased estimator, $E(\mu_hat) = \mu$



# Variance of Distributions

## Variance
Variance is a measure of spread. It is the **average squared distance from the mean**.
Squared because if we just took a plain average, the pluses and minuses would always cancel out and give 0. We *could* take the magnitude, but the discontinuity at x=0 makes the maths less nice, so by convention we usually use squared distances. This is the same argument as L1 vs L2 norm.


$$
Var(X) = E[(X - E(X))^2]
       = E[X^2 - 2XE(X) + E(X)^2]  Expanding brackets
       = E(X^2) - 2E(X)E(X) + (E(X))^2  Linearity of expectation
       = E(X^2) - E(X)^2
$$


## Variance of a Bernoulli Distribution 

Remember that in the general case, the variance is defined as:

$$
Var(X) = E(X^2) - E(X)^2
$$

We already know the mean of a Bernoulli distribution is $E(X) = p$
So we just need to find an expression for $E(X^2)$.

Recall that for a Bernoulli distribution:
$$
f(x) = {p,    x=1
        1-p, x=0
        0,     otherwise
$$

So 
$$
E(X^2) = \sum x^2P(X=x)
       = 0*0*(1-p) + 1*1*p
       = p 
$$

Substituting into our variance formula:
$$
Var(X) = E(X^2) - E(X)^2
       = p - p^2
       = p(1-p)
$$

So the variance of a Bernoulli distribution is $Var(X) = p(1-p)$.


## Variance of a Uniform Distribution 

Again we start with that general formula for variance
$$
Var(X) = E(X^2) - E(X)^2
$$

We know the the expected value for a uniform distribution is $\theta / 2$ and the PDF is $f(x) = 1 / theta$

So $E[X}^2 = \theta ^ 2 / 4$. We just need to calculate $E[X^2]$.
$$
E[X^2] = \int_{x=0}_{\theta} x^2 (1 / \theta) dx
       = (1 / \theta) \int_{x=0}_{\theta} x^2  dx  Pulling constant terms outside the integral
       = (1 / \theta) x^3 / 3 |_{\theta}_{0}
       = \theta ^2 / 3 
$$

Hence our variance expression is:
$$
Var(X) = E(X^2) - E(X)^2
       = \theta ^2 / 3 - \theta ^ 2 / 4
       = \theta ^ 2 / 12
$$     


## Variance of a Normal Distribution 

You can grind through the integrals to get an expression for the variance... we know that it will eventually simplify down to $Var(X) = \sigma ^2$ by the definition of a Normal distribution.



# Variance of Estimators

## Why the Variance of an Estimator Matters

We want a lower variance for our estimator, i.e. the value we measure is in a tighter range near the true population mean.

An estimator with an unbiased mean but massive variance wouldn't be very useful. On average, the survey results will reflect the true results, but any given survey may be wildly off the true population mean.


## Properties of Variance

Similarly to the linearity properties of expected value, there are analogous results for variance.

If we scale our random variable by a constant, the variance squares all distances, so:
$$
Var(cX) = c^2 Var(X)
$$


For iid random variables:
$$
Var( \sum X_i ) = \sum Var(X_i)
$$



## Variance of the MoM Estimator of a Bernoulli Distribution 

Recall that the MoM estimate is:
$$
p_hat = x_bar = \sum_{i=1}_{n} x_i / n
$$

We want to find the variance, so rewrite it in a form where we can apply some of our variance rules:
$$
Var(p_hat) = Var( \sum_{i=1}_{n} x_i / n)
           = 1/n^2 Var(\sum_{i=1}_{n} x_i)  using the result Var(cX) = c^2Var(X)
           = 1/n^2 \sum_{i=1}_{n} Var(x_i)  using variance of sum = sum of variances (for iid)
           = 1/n^2 \sum_{i=1}_{n} p(1-p)    using the result for variance of a Bernoulli variable 
           = 1/n^2 np(1-p)
           = p(1-p) / n
$$

So $Var(p_hat) = p(1-p) / n$
This means the variance always decreases with $n$ more samples. 
The lowest variance is for $p=0.5$; if positive or negative cases is very likely (e.g. 0.99) then we wouldn't see much variance in our estimate because it is so certain. In the extreme case of p=0 or p=1, the variance is 0.


## Variance of the MoM Estimator of a Uniform Distribution 

Recall the the MoM Estimator is:
$$
\theta_hat = 2 x_bar = 2 \sum_{i=1}_{n} x_i / n
$$

We want to find an expression for the variance:
$$
Var(\theta_hat) = Var(2 \sum_{i=1}_{n} x_i / n)
                = 4/n^2 Var(\sum_{i=1}_{n} x_i)  using the result Var(cX) = c^2Var(X) 
                = 4/n^2 \sum_{i=1}_{n} Var(x_i)  using variance of sum = sum of variances (for iid)
                = 4/n^2 \sum_{i=1}_{n} \theta ^ 2 / 12  using the variance of a uniform distribution
                = 4/n^2 * n * \theta ^ 2 / 12
                = (\theta ^ 2) / 3n 
$$


This makes intuitive sense. As the distribution gets wider, the variance gets wider. As the number of samples increases, the variance decreases, i.e. we get a more certain estimate.


## Variance of the MoM Estimator of a Normal Distribution 

Recall that 
$$
\mu_hat = x_bar = \sum_{i=1}_{n} x_i / n
$$

So the variance is:
$$
Var(\mu_hat) = Var( \sum_{i=1}_{n} x_i / n)
             = 1/n^2 Var(\sum_{i=1}_{n} x_i)  using the result Var(cX) = c^2Var(X) 
             = 1/n^2 \sum_{i=1}_{n} Var(x_i)  using variance of sum = sum of variances (for iid)
             = 1/n^2 \sum_{i=1}_{n} \sigma^2  using the variance of a Normal distribution
             = 1/n^2 * n * \sigma^2
             = \sigma^2 / n
$$


This gives the well-known result that for a normally-distributed random variable $X_i ~ N(\mu, \sigma ^ 2)$, the mean of N such iid random variables is:
$$
X_i ~ N(\mu, \sigma ^ 2 / N)
$$

This comes up a lot in hypothesis testing because of the central limit theorem.


# Maximum Likelihood Estimation

## Intuition
This is an alternative approach to finding estimators to the Method of Moments approach.

The idea is that we shift our perspective so that rather than thinking of pdfs as a function of the data $x$ where parameters $\mu$ and $\sigma$ are unknown, we treat it as a function of the parameter $\mu$ where our observed data $x$ is known.

Typically we would think of the PDF for some distribution where $\mu = 2$ and $\sigma = 3$ as:
$$
f(x) = \frac{1}{\sigma\sqrt{2\pi}} 
  \exp\left( -\frac{1}{2}\left(\frac{x-\mu}{\sigma}\right)^{\!2}\,\right)
}
     = \frac{1}{3\sqrt{2\pi}} 
  \exp\left( -\frac{1}{2}\left(\frac{x-2}{3}\right)^{\!2}\,\right)
}
$$

Instead, say we have observed one data point where $x_1 = 4$. We treat $\mu$ as the unknown and rewrite this as the **likelihood function**:
$$
L(\mu) = \frac{1}{\sigma\sqrt{2\pi}} 
  \exp\left( -\frac{1}{2}\left(\frac{4-\mu}{\sigma}\right)^{\!2}\,\right)
}
$$

Then to find a good estimate of the parameter, we find the maximum of the likelihood function.


In summary:

- PDF: Known parameters, unknown data
- Likelihood: Unknown parameters, known data.


## Joint PDF

The probability of two things happening in succession is the **joint probability**.

For example, the joint probability of flipping two heads is
$$
P(H,H) = 0.5 * 0.5 = 0.25
$$

This is true of any number of (independent) events.
So if we have observed some data $(x_1, x_2, ... x_n) = X%
Then we can think about the joint probability distribution of all of these events $P(X)%.

$$
f(X) = \product_{i=1}_{n} f(x_i)
$$

Assuming all of the data ($x_i$s) are iid, i.e. the same distribution parameters for the following. 
For a Bernoulli distribution, the joint PMF is:
$$
f(X) = \product_{i=1}_{n} f(x_i)
     = \product_{i=1}_{n} p^{x_i} (1-p)^{1-x_i}
     = p^x_1(1-p)^{1-x_1} . p^x_2(1-p)^{1-x_2} ... p^x_n(1-p)^{1-x_n}  Expanding out
     = p^{\sum x_i} (1-p)^{\sum 1 - x_i}  Collecting terms
     = p^{\sum x_i} (1-p)^{n - \sum x_i}  Simplifying    
$$


For a Uniform distribution, the joint PDF is:
$$
f(X) = \product_{i=1}_{n} f(x_i)
     = \product_{i=1}_{n} 1 / \theta
     = 1 / \theta^{n}
$$

For a Normal distribution, the joint PDF is:
$$
f(X) = \product_{i=1}_{n} f(x_i)
     = \product_{i=1}_{n} (2 \pi \sigma^2)^{-1/2}) e^{-(x-\mu)^2 / 2 \sigma^2}
     = (2 \pi \sigma^2)^{-n/2}) e^{-\sum{I=1}_{n} (x-\mu)^2 / 2 \sigma^2}
$$

We often call the joint PMF/PDF the "joint distribution".

Remember that the "likelihood function" is just this same formula, but reframing what we see as the knowns vs unknowns. We treat the parameter as an unknown and the data as a known value.


## Finding the MLE
We differentiate the likelihood function to find the maximum.


Because the likelihood function $L(\theta)$ is a joint distribution, it will often contain lots of products and exponentials.
It is therefore often more convenient to work with the **log-likelihood function** $l(\theta)$ since logs convert products to sums which are easier to differentiate. We use the natural log to deal with the $e$ values that often crop up.
$$
l(\theta) = log(L(\theta))
$$

The log function is **monotonic**, so the maximum of $l(\theta)$ occurs for the same value of $\theta$ as $L(\theta)$, i.e. we are still maximising our original likelihood function even if we use the log-likelihood in our calculations for tractability.


To find the maximum of the log-likelihood, we set it's derivative to 0 and solve for $\theta$:
$$
d l(\theta) / d \theta) = 0
$$

The derivative function is sometimes called the "score function".


## Properties of logarithms

Log of products = sum of logs
$$
log(xy) = log(x) + log(y)
$$

Log of exponents
$$
log(a^b) = b log(a)
$$

And by extension
$$
log(1 /a) = log(a^{-1}) =  -log(a)
$$


## MLE Estimator for a Bernoulli Distribution

The general process is:
```
PDF -> Joint PDF -> Likelihood function -> Log-likelihood function -> Maximise it
```

Recall that our PDF is:
$$
f(x_i) = p^{x_i} (1-p)^{1-x_i}
$$

And our joint PDF when taking the product of multiple random Bernoulli variables is:
$$
f(X) = p^{\sum x_i} (1-p)^{n - \sum x_i}
$$

Our likelihood function is just rewriting this joint PDF as a function of the parameters. Just the same thing.
$$
L(p) = p^{\sum x_i} (1-p)^{n - \sum x_i}
$$

Our log-likelihood is then:
$$
l(p) = log L(p) = \sum x_i log(p) + (n - \sum x_i) log(1-p)
$$

Now to find the maximum.
$$
dl/dp = \sum x_i / p - (n - \sum x_i) / 1-p = 0
$$

The solution to this is $p_hat_{MLE}.
$$
Multiply both sides by p(1-p)
\sum x_i (1-p) - (n - \sum x_i) p = 0

Expand sums
\sum x_i - p sum x_i - np + p \sum x_i = 0

Collect p terms
p (- sum x_i -n + sum x_i) + sum x_i = 0
=> sum x_i = np
=> p_hat = \sum x_i / n = x_bar
$$

So the MLE estimate of p is the same as the MoM estimate: $x_bar$.


## MLE Estimator for a Uniform Distribution

The PDF of each observation (random variable) $x_i$ is:
$$
f(x_i) = 1 / \theta  , 0 <= x_i <= \theta
       = 0           , otherwise
$$

The joint PDF is then the product of these:
$$
f(X) = \product_{i=1}_{n} f(x_i) = 1/ \theta ^ n  , 0 <= x_i <= \theta for all x_i
                                 = 0 otherwise
$$

The bound is important as it determines when this function is valid, which we need to consider when maximising the likelihood function. Note that **all** of the $x_i$ values need to be in the bound, otherwise the product, i.e. the entire joint PDF, is 0.

The likelihood function is just reframing the joint PDF as a function of $\theta%.
$$
L(\theta) = 1/ \theta ^ n  , 0 <= x_i <= \theta for all x_i
          = 0 otherwise
$$

We often take the log at this point to make the differentiation more tractable, but in this case we don't need to.

We can plot $L$, or differentiate it, to realise that the value of \theta asymptotically approaches infinity as \theta approaches 0.
$$
dL / d \theta = -n \theta ^{n-1}
$$

<TODO: plot of L(\theta)>

So is $\theta_{MLE} =0$? Naively we would think so, but remember the bounds of the PDF. \theta has to be at least as high as the observations we have seen for the PDF to be valid. So the maximum of the observed $x_i$ values is a lower bound. We can write this as $x_{(n)}$, where the brackets indicate this is the nth element in the sorted list. The smallest allowable value of $\theta$ maximises this function.

Therefore $\theta_{MLE} = max x_i$.

Note that this is different to our MoM estimate, which said that $\theta_{MOM} = 2 x_bar$. 
MLE bases the estimate of the upper bound parameter $\theta$ on the maximum value we have seen. MoM says to take the average we have observed, that should be somewhere near the middle, so we double it to get an estimate of the upper bound parameter $\theta$.

We know that $\theta_{MOM}$ was unbiased, so $\theta_{MLE}$ must be biased.


## Mean Squared Error

We used bias and variance to evaluate the goodness of our estimators.

We may want to compare a biased estimator vs an unbiased estimator. One method for doing so is to compare the mean squared error (MSE); the average squared distance from the true value.

$$
MSE(\theta_hat) = E[(\theta_hat - \theta)^2)
$$

We can work through some algebra to get the identity:
$$
MSE(\theta_hat) = Bias(\theta_hat) ^2 + Var(\theta)
$$

So for an unbiased estimator, the MSE = Variance.

Biased estimators can still be useful. We want estimators which are close to the mean with small variance. We may have an unbiased estimator which has a large variance. An alternative biased estimator with small bias but much tighter variance could be more useful.


## MLE Estimator for a Normal Distribution

Recall that for a Normal distribution, the joint PDF is:
$$
f(X) = (2 \pi \sigma^2)^{-n/2}) e^{-\sum{i=1}_{n} (x-\mu)^2 / 2 \sigma^2}
$$

So the likelihood is just reframing this as a function of the parameter $\mu$:
$$
L(\mu) = (2 \pi \sigma^2)^{-n/2}) e^{-\sum{i=1}_{n} (x-\mu)^2 / 2 \sigma^2}
$$

Since we are taking logs the constant term at the front becomes an addition, and then the derivative of a constant is 0. So we can ignore it.
The log-likelihood function is then:
$$
l(\mu) = -1 / (2 \sigma^2) \sum{i=1}_{n} (x-\mu)^2 
$$

To find the maximum, we take
$$ the derivative and set it to 0.
dl / d \mu = -1 / (2 \sigma^2) \sum{i=1}_{n} 2(x-\mu) = 0
=> \sum{i=1}_{n} (x-\mu) = 0
=> \sum{i=1}_{n} x - (n* \mu) = 0
=> \mu_hat = \sum{i=1}_{n} x / n
           = x_bar
$$

So this is the same as the MoM estimator, $\mu_hat = x_bar$.



# Fisher Information and Cramer Rao Lower Bound (CRLB)


CRLB gives a proven lower bound for the variance of an estimator for certain distributions (in the exponential family). The starting point for this is to consider the information contained in one observation about our parameter $\theta%.
This is encompassed in the **Fisher Information**, defined as:
$$
I_1(\theta) = -E[l''(\theta)]
$$

For $n$ observations, this scales as:
$$
I_n(\theta) = n I_1(\theta)
$$

The intuition behind this is to think about the distribution for an estimator. For a very informative estimator, it is a tight distribution around the true value. So the curvature of the likelihood is high; it increases and then decreases rapidly either side of the true value. So the second derivative of the likelihood function tells us how tight the estimator is around the true value.

The **Cramer Rao Lower Bound (CRLB)** then tells us that the lower bound for the variance is:
$$
Var(\theta_hat) >= 1 / I_n(\theta)
$$

So if we can show that this bound is tight for a particular estimator and that the estimator is unbiased, the estimator is **efficient**.



## CRLB for a Bernoulli Distribution 

Recall that in general for any distribution:
$$
Var(\theta_hat) >= 1 / n*I_1(\theta)
I_1(\theta) = -E[l''(\theta)]
$$


For a Bernoulli distribution:
$$
f(x) = p^{x} (1-p)^{x}
L(p) = p^{x} (1-p)^{x}
l(p) = xlog(p) + (1-x)log(1-p)
dl/dp = x/ p - (1-x)/(1-p)

$$

The Fisher Information is then found for a single observation by taking the second derivative and finding its expected value.
$$
d2l/dp2 = l''(p) = -x/p^2 - (1-x)/(1-p)^2
$$

The expectation over x, using $E[x] = p$ for a Bernoulli:
$$
E[l''(p)] = E[ -x/p^2 - (1-x)/(1-p)^2]
          = -p / p^2 - (1-p)/(1-p)^2
          = - 1/p - 1/(1-p)
          = - 1 / p(1-p)
$$

The Fisher information is the negative of this, i.e. $I_1(p) = -E[l''(p)] = 1 / p(1-p)$

The CRLB is the reciprocal, i.e. $CRLB = 1 / nI_1(p) = p(1-p) / n$

This is the variance we found for both our MoM and MLE estimators, therefore these estimators are efficient.


## CRLB for a Uniform Distribution 

The definition of Fisher Information only applies when the support (i.e. the sample space of the distribution) does not depend on the value of $\theta$. This condition is breached for the uniform distribution.

The uniform distribution is not a member of the exponential family.


## CRLB for a Normal Distribution 

As in the general case, we need to find the log-likelihood function, then calculate its second derivative.

$$
l(\mu) = log(1/(sqrt(2 \pi \sigma^2)) + (-1 / (2 \sigma^2) (x-\mu)^2 )
dl / d\mu =                           + (x-\mu) / \sigma^2 
L''(\mu) = -1 / \sigma^2
$$

The Fisher Information for a single observation is therefore:
$$
I_1(\mu) = -E[-1 / \sigma^2]
         = 1 / \sigma^2  Since none of this expression is random
$$

The CRLB is therefore 
$$
Var(\mu) >= \sigma^2 / n
$$

So our Mom and MLE estimators are both efficient.


## Efficiency

We can define the **efficiency** of an estimator as the ratio of it's variance and its optimal variance given by the CRLB:
$$
Efficiency(\theta_hat) = CRLB / Var(\theta_hat)
$$

We can also compare two different estimators by taking the ratio of their variances. This is the **relative efficiency**. For example, comparing the MOM and MLE estimators:
$$
Relative Efficiency = Var(\theta_hat_{MOM}) / Var(\theta_hat_{MLE})
$$

This is typically a function of $n$. We can analyse the **relative asymptotic efficiency by observing the behaviour as $n -> \inf$.



# Central Limit Theorem

This relates to the **asymptotic distribution** of our estimators. 

We previously discussed that the estimator of a random variable is itself a random variable, which meant we could analyse its expected value and variance. We can go a step further; rather than just analyse these summary statistics of the estimator, let's analyse the whole distribution.

The *asymptotic* behaviour means the distribution as our sample size $n -> \inf$.
This obviously can never occur in practice, so as a rule of thumb when $n>=30$ the CLT is approximately true.

Once we know the distribution of the parameter, we can reason about the probability that the parameter takes a certain value. This is the idea behind hypothesis testing.

The CLT states that for a large enough sample size, the distribution of the parameter is approximately normal. It applies when the estimator is a sum of average of random variables. This is true of a lot of estimators. One notable exception is the MLE estimate for a uniform	 distribution, as this was the _maximum_ of the data points, so the CLT does not apply.

For most distributions, the rule of thumb for CLT to apply is $n >= 30$. For a Bernoulli distribution, the condition is $np >= 10, n(1-p) >= 10$.
For a Normal distribution, the parameter is **exactly** Normal regardless of sample size, so we don't need CLT.



## CLT for a Bernoulli

Recall that both MOM and MLE estimators for a Bernoulli distribution were $p_hat = x_bar$.

As this is an *average* of data points, CLT applies.
A general rule of thumb is that CLT applies when the expected number of successes $np > 10$ and the expected number of failures $n(1-p) > 10$.

We've already established the mean and variance of the estimator $p_hat$ in earlier sections:
$$
E[p_hat] = p
Var[p_hat] = p(1-p) / n
$$

So the value of the estimator is a Normally distributed random variable with those parameters. We now know the entire distribution and can do interesting things with it, like hypothesis testing.

The CLT approximation is helpful because the Normal distribution can often be easier to compute than the original distribution, so it reduces the computing power (or historically, the number of calculations required by hand), while still giving a good approximation to the true value if we had used the actual distribution.


## CLT for a Uniform

We only consider the MOM estimate not the MLE estimate, because the MLE estimate was a **maximum** of values, meaning the CLT does not apply.

We can reason about the asymptotic distribution of the MOM estimate for a uniform distribution if our sample size is large enough $n>30$.

We've already established the mean and variance of the estimator $\theta$ in earlier sections:
$$
E[\theta_hat] = \theta
Var[p_hat] = \theta ^2 / 3n
$$

So again, our estimate is a Normally-distributed random variable with these parameters.


## CLT for a Normal

When we add Gaussians we get another Gaussian, so the actual (rather than asymptotic) distribution of our estimator for a Normal distribution is **exactly** Normal.
 
We don't need any specific sample size for this to be true; it is true for $n=1,2,3,...$, we don't need our usual rule of $n>30$.

We've already established the mean and variance of the estimator $\mu$ in earlier sections:
$$
E[\mu_hat] = \mu
Var[\mu_hat] = \sigma ^2 / n
$$

So again, our estimate is a Normally-distributed random variable with these parameters.

Note that we don't need a minimum sample size $n$ for the CLT to apply, but a large $n reduces the variance of our estimate, thus reducing our uncertainty.


## Consistency

Consistency is another measure of asymptotic behaviour that says that as the number of samples approaches infinity, the estimator converges to the true value of the parameter.

Mathematically
$$
P(| \theta_hat - \theta | < \epsilon) -> 1  as n -> \inf
for \epsilon arbitrarily small
$$

Unbiased estimators are **consistent** if their variance approaches 0 as n approaches infinity.


# Confidence Intervals

When we've looked at estimators in previous sections, we've focused on **point estimates**. 

But we know that these are random variables, so we would prefer to make **interval estimates**. Then we can make statements like "we are 95% sure that the mean is between 1.5 to 2.5".

We can use the results from previous sections for this. Recall that we were able to reason about the distribution of our estimate with CLT. The *estimate* $\theta_hat$ is centred on the true value, and using the $2 \sigma(\theta_hat)$ value, there is a 95% probability that the estimate lies within 2 (sample) standard deviations of the true mean.
Mathematically:
$$
P(\theta - 2\sigma(\theta_hat) <= \theta_hat <= \theta  2\sigma(\theta_hat)) = 0.95
$$

Note that we have the population parameter value $\theta$ in the left and right terms and the *sample* value $\theta_hat$ in the middle term.

We want to shift our perspective when going from probability to statistics. In statistics/the real world, we *don't know* the TRUE parameter value, but we can gather data so that our ESTIMATED parameter value is known. So we want to make confidence interval statements about the true value, i.e. we want the population value $\theta\$ in the middle of the inequality and estimated values $\theta_hat$ as the bounds.

We can do this with a bit of algebra. Starting with the equation above, subtract $\theta$ and $\theta_hat$ from each term inside the probability. 
$$
P(-\theta_hat - 2\sigma(\theta_hat) <= \theta <= -\theta_hat + 2\sigma(\theta_hat)) = 0.95
$$

Now multiply all terms by -1 and note that it flips the sign of the inequality when we multiply by a negative value.
$$
P(\theta_hat + 2\sigma(\theta_hat) >= \theta >= \theta_hat - 2\sigma(\theta_hat)) = 0.95
$$

This was our goal: we now have bounds for the **population** value $\theta$ in terms of the estimated values $\theta_hat$ which are known values that we can calculate from the data.

We have **inverted/pivoted** the roles of $\theta$ and $\theta_hat$.


What does it mean to have a 95% confidence interval? Say we have a process:

1. Collect data
2. Calculate the confidence interval
3. Theoretically repeat this process over and over

So we are doing 20 coin flips. We get a confidence interval [0.4, 0.45]

Then we do 20 more flips and get a confidence interval [0.48,0.53]

Then a third time we do 20 flips and get a confidence interval [0.46, 0.55]

And we keep going... We get a list of confidence intervals:
$$
[0.4, 0.45]
[0.48,0.53]
[0.46, 0.55]
[0.49, 0.56]
[0.42, 0.50]
[0.45, 0.55]
...
$$

Our 95% value means **"95% of these hypothetical intervals calculated will contain the true parameter value $\theta$"**.


## The pivot from probability to statistics

The pivot from probability to statistics was mentioned in the previous section but is crucial so bears emphasising.

In probability, we can make statements like "there is 95% probability that $\theta_hat$ is in $\theta +- 2 \sigma(\theta)$".

In statistics, thanks to our pivot (algebraic manipulation of the inequality), we make statements like "we are 95% confidence that $\theta$ is in the interval \theta_hat +- 2 * standard error(\theta_hat)$".


## Some useful terms

The sample standard deviation, e.g. $\sigma_hat / sqrt(n)$ is called the **standard error**.

The **margin of error** for a particular confidence interval statement is the standard error multiplied by the number of standard deviations we use. For example, for a 95% confidence interval
$$
Margin of error = 2 * Standard error
$$ 


## Bernoulli Confidence Intervals

We've already established the mean and standard error of our MOM/MLE estimators (they were the same for Bernoulli).

So our 95% confidence interval is
$$
p_hat +- 2 sqrt(p_hat (1-p_hat) / n )
$$


## Uniform distribution confidence intervals

We skip the MLE uniform estimator since it's a maximum of values, therefore CLT does not apply and we cannot reason in the same way. 

For our MOM estimator, the 95% confidence interval is:
$$
\theta_hat +- 2 * \theta / sqrt(3n)
$$


$$ Normal distribution confidence intervals
For our MOM estimator, the 95% confidence interval is:
$$
\mu_hat +- 2 * \sigma / sqrt(n)
$$



<Add links to all practice worksheet pdfs>