---
title: "Executive Presence"
description: "My Presence is a Present"
date: "2025-05-22"
categories: [Business, Leadership]
---

# 1. Your Personal Inventory

Identify personal blocks. 


## 1.1. Assessing Yourself
Self-reflection is important, just beware of “the judgement zone”. 

You are not the same person you were at 9 years old, 20 years old, 21 years old. You are always changing. Be compassionate towards yourself. Compassionate, curious and committed. 

Identify your strengths and “stretches”; where you can grow. 
But these “stretch” areas change over time because you will improve and change. 


## 1.2. Your Mind

What is your habitual mind state? Do you see yourself as “less than”, shy, or some other negative trait?

“The chains of habit are too light to be felt until they’re too heavy to be broken.”


## 1.3. Cognitive Corrections

There are several “errors in thinking” that cause us to be depressed:

- Minimise positives and maximise negatives. 
- Overgeneralise.
- Future telling. Assume you’re going to mess something up, which makes you more likely to mess it up. 
- Mind reading. You assume everyone thinks you’re terrible.
- You **“should”** yourself. “I *should* be doing better", "I *should* make no mistakes", "I *should* be fluent in this”, etc.


This is a vicious cycle; once a few negative thoughts creep in, we might make a mistake and reinforce this view so more negative thoughts flood in. 

The way to correct this is to **think objectively**. It can be helpful to do this *in writing*. Being objective doesn’t mean being blindly positive. Write down a negative thought and ask a close friend what they think about it - do they agree?


## 1.4. Your Voice

Things that are making us seem less confident:

- Rising intonation when things aren’t questions. Address this by imagining a big full stop at the end of your sentence. 
- Filler words - "umm, err, like". *Stop and pause* instead of using filler words. 
- High pitched voice.


### 1.4.1. Vocal Checklist
Record yourself speaking and identify which of the following vocal checklist applies to you:

- Airy or breathy
- Soft-apoken
- Whimsical
- Fast
- Slurred or tired
- Over-articulated
- Warm
- Relaxed and comfortable
- Hoarse
- Honky
- Hyper-nasal
- Harsh
- Strained
- Raspy
- Wobbly
- Loud
- Chesty
- Child-like
- Sultry


### 1.4.2. Vocal Warmup

Warm up your breathing:

- Connect to your breath. Notice your breath and let it drop down to your diaphragm. 
- Relax your belly. Rub your belly with your hands.
- Send your breath down to your toes. 
- Breathe in through nose and sigh out through mouth.


Warm up your face: 

- Bring your voice forward to the front of your mouth. Roll your tongue forcefully behind your lips. 
- Blow air through lips on a sigh. This should flap your lips. 


Warm up your lips:

- Hum on a sigh. Feel the buzzing on your lips. 
- Send the humming vibrations to a spot in front of you. 


Warm up your nasal resonators:

- Create a bright “me” sound and push it out of your nose and the middle of your face. 
- Send the sound through your cheekbones. Use your hands to touch your cheeks in rhythm with the “me” sound to help engage them. 


Warm up your chest resonators:

- Connect to your chest while making a “maaah” and “haah” sounds.
- Thump on your chest as you do it to engage it. 


Warm up your articulators:

- “Topeka” x3 and “bodega” x3.
- Alternate the sounds. Play with pitch and rhythm. 


Integrate your voice:

- Slide sound from head (nasal resonators) down to chest resonators, then out through mouth .
- “Me me me me me me my my my my ha hum ma”.


## 1.5. Your Body

Exercise more, you’ll naturally stand up straighter. 

Pilates and intentional breathing is helpful. Two useful Pilates exercises are “hundreds” and the bridge. 

Think of the core not just as the abs, but everything from the pelvic floor up to the neck. 


# 2. Building Confidence 

**Energy muscle testing**. You are physically weaker when you are lying or dishonest.


Instant confidence trick. What is your **superhero name**? What would your soundtrack be?


**Affirmations**. “Your power post it”. Take a habitual negative thought, and write the opposite positive statement. Write it on a post it and put it in lots of places that you’ll see often. It doesn’t matter if you don’t even believe it, it will start to influence how you feel about that trait. 

The *attitude of gratitude*. Cultivate gratitude by keeping a gratitude journal. For three weeks, keep a journal where you write 3 things you’re grateful for today. 


# 3. The Art of Casual Conversation 

There is a **distinction between “small talk” and casual conversation**. Most people dislike small talk because it feels pointless. But we are social beings and require social interaction, and some of those interactions should be casual. 

Digital distractions. We can’t connect with the people around us if we’re glued to our phones. Be the change you want to see in the world: put your phone away and give your undivided attention to the people around you. 


How to make a great first impression:

- Firm handshake 
- Strong eye contact 
- Warm smile. What is your resting “mask”, i.e. your face? For example, some people have resting bitch face. 


Dealing with difficult conversations:

- Try to interject a positive spin
- You can always leave
- Positive people attract positive people, negative people attract negative people


Casual conversation is a muscle; practice it in low stakes situations. Go to events you wouldn’t otherwise just to practice. 

**Connection is about listening**. Don’t just focus on what you’re going to say next. Hear what they have to say. 


# 4. Sales

## 4.1. Everything is Sales
**Everything is selling** even if you don’t realise it. If you are recommending a place to eat, or talking about yourself or selling a product, it’s the same idea. 

Reframe selling as being in service to the other person. You’re doing them a favour. 

Remind yourself:

- You have amazing gifts to share with the world
- People love to be inspired
- Your work is your service to other people 


## 4.2. Find Your Spark

What is an activity that gets you “in the zone”, in a state of flow? What is it about that activity that does it for you? What are the things that light you up?

When you are in the zone, you are not self-doubting, overly critical, etc. Try to mimic that confidence when you’re not in a flow state; you know you are capable of it. 

```
I am in the zone when…

In the zone I am…

At work, I love to…
```

When you’re communicating, e.g. giving an elevator pitch about yourself, it’s not just a list of facts you’re communicating. Think about what gets you in a flow state and get that across to the other person. 


## 4.3. The Elevator Pitch

The goal isn’t to information dump, it’s to **spark curiosity** so that the other person wants to carry on talking to you after the elevator ride is over. 


> The purpose of an elevator pitch isn't to close the sale. The goal isn't even to give a short,
> accurate, Wikipedia-standard description of you or your project. And the idea of using
> vacuous, vague words to craft a bland mission statement is dumb. No, the purpose of an
> elevator pitch is to describe a situation or solution so compelling that the person you're with
> wants to hear more even after the elevator ride is over.

\- Seth Godin


How do you typically describe what you do?

Think about *what your spark is* and then rewrite your elevator pitch with that at the centre. 
Then practice the new pitch. 

The **sign of a successful elevator pitch is that they ask you questions**. You’ve hooked them and they want to know more. 


## 4.4. Listening

How to listen your way to more friends/sales:

- Shift your attention from yourself (and what you plan to say next) to the other person
- Be present
- Ask questions - “what brings you here?” is open-ended enough to get to the heart of what they need not just what they’re doing. 
- Let the conversation flow, don't force it back to your topic / product
- Be generous - “Who can I help?”. Help others and they'll want to help you.


## 4.5. How to Identify Your Ideal Client 

Lots of sales approaches try to cast too wide a net - “anybody is a potential client”. 
Adopt an **abundance mindset** - *“there are so many potential clients out there that I can be picky”*.


Ask yourself the following questions to figure out your ideal client:

- Which clients have you enjoyed working with the most? How would you describe them? What was your experience working together?
- What aspect of your work truly lights you up?
- What problems did they have that you solved? How did you impact their lives?


Then write a client avatar for that ideal client:

- Name
- Age
- Profession
- Challenge/Need/Frustration
- What are their fears?
- What are their desires and dreams?
- Why do they need you?
- How do they feel working with you?


## 4.6. Dealing with Rejection 

How do you deal with rejection? You can’t control being rejected but you can control your response to it. 

- Don’t take it personally.
- Feelings are not facts. Just because you feel like you failed, you performed badly, etc, doesn’t mean you are bad at what you do. 
- Pause before reacting.


Processing rejection:

- Write. Brain dump your feelings. 
- Shower. 
- Flick. If you have the urge to beat yourself up, put an elastic band on your wrist and flick yourself whenever you feel bad and move on. 


# 5. How to Present

## 5.1. Picture the stage

Allow yourself to dream big. What is your ideal stage you would want to be on?

Often the same limiting thoughts that tell us we aren’t good at presenting or public speaking are the same root cause as those stopping us from speaking our mind in meetings or asking for a promotion. 


## 5.2. How to Interview

Think about what you love, **your “why”**. You don’t need a script, but you need to be able to articulate this. 

Communicate **how** you do it. Think about a nice sound bite, especially if it’s a media interview. Short and sweet message. 

Pay attention to what the other person is saying. Don’t be so focused on yourself that you don’t engage with the other person. 

Practice interviewing in lower stakes situations. 


## 5.3. PowerPoint Presentations 

Less is more. 

**We remember stories, not information**. Your job isn’t to dump information, it’s to tell a story. 

- What is your story?
- The targeted takeaway. What do you want the audience to remember? What action should they take?
- Toss the script. Create thought bubbles around high level ideas that you can talk around them spontaneously. Instead of a script, it’s a journey through thoughts, like acts in a story. One thought bubble per slide keeps the message clear. 


Preparing your presentation:

1. Identify your goal. **What should the audience feel or do**?
2. What stories illustrate your point?
3. What images are absolutely necessary to support your point?
4. What thought bubbles walk your audience through your message?
5. What are the transitions to get from one thought bubble to the next?


Suggested TED Talks:

 - Susan Cain: The Power of Introverts
 - Brene Brown: The Power of Vulnerability
 - Amy Cuddy: Your Body Language Shapes Who You Are


## 5.4. Preparation exercises 

- Smile
- Breathe
- Engage. Look at the audience. Look at the back row. Pick a friendly face; some may look disinterested but find the ones that are keen. 
- Prepare. Use notes as necessary. 
- Visualise. Imagine the presentation going well and the audience responding well. 
- Let go. You may not see immediately whether people have taken your message on board and you may never see the impact directly. Trust that your message will have an impact. You can control your contribution but not the outcome. 


## 5.5. Dealing with Anxiety

- Deep breathing. Physiological sighs. 
- Visualisation. Picture the presentation and the audience’s positive reaction. Notice the details of the room. 
- Listen to relaxing sounds and music. 


## 5.6. Holding the Neuro

The **neurovascular points** are the ridges above the eyes. They regulate the flow of blood in the body and bring blood to the thinking brain. 

When you are under stress, less blood goes to the frontal area of your brain. Rubbing the neurovascular points and temples can stimulate more blood flow. Do this while breathing deeply. 

A hand on the forehead and the other hand on the back of the neck can also help. 

This can also help when processing trauma. 


# 6. On Camera 

## 6.1. Being Comfortable on Camera

Practice in low stakes situations. FaceTime calls are the same basic idea as being on camera, so get used to it. Practice looking at the camera not the person; looking at a camera lens is weird and unusual so practice it. 


## 6.2. Types of Videos
Suggestions of business video content:

- Product demonstrations
- About me
- New product and service launches
- Homepage
- Meet the team
- Behind the scenes
- Weekly video blogs
- Frequently asked questions
- Market updates
- Reviews

Think about the videos you like and dislike. 


Tips:

- Know your viewer
- Keep it short and sweet
- Love the lens
- Use calls to action
- Practice 


# References

- [Alexa Fischer's Udemy course](https://www.udemy.com/share/101Weg3@3l7GgCCLxBnbMRwbGeQXSx-OnSTxH6q7YzS8kP-oWEbojlZJoOKRy3-PYaojTp4V/)
- [Workbook](1000WattPresenceFullWorkbook.pdf)
- Executive Presence 2.0 by Sylvia Ann Hewlett